### PR TITLE
fix: allow magnet protocol in href

### LINKED ISSUE #1191: 链接不支持 磁力
使用 `[]()` 插入链接 或者使用 html a标签 写了 src="magnet.?/xxxx" 的时候, 保存后 链接会被吃掉 导致不能点击

### PR DESCRIPTION
**Pull request by hyoban**
### WHAT

copilot:summary

copilot:poem

### WHY

close #1191 

### HOW

copilot:walkthrough

### CLAIM REWARDS

For first-time contributors, please leave your xLog address and Discord ID below to claim your rewards.

### CODE REVIEW

File: src/markdown/sanitize-schema.ts [hunk 1]
```diff
@@ -1,9 +1,8 @@
+import deepmerge from "deepmerge"
```
Comment (DIYgod) [inline src/markdown/sanitize-schema.ts:1]: I think maybe `structuredClone` can be used as a replacement for it.

**Review by DIYgod — CHANGES_REQUESTED** [review]

File: src/markdown/sanitize-schema.ts (hunk 1 above)
Comment (hyoban) [reply src/markdown/sanitize-schema.ts:1]: `structuredClone` should be used to obtain a copy of the object?
Here it is expected to merge the properties of the object so that we do not need many levels of `...`.

Comment (DIYgod) [reply src/markdown/sanitize-schema.ts:1]: [structuredClone](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) is a native deep cloning function, so we don't need to introduce a new dependency library.

Comment (hyoban) [reply src/markdown/sanitize-schema.ts:1]: Sorry, I may not have expressed myself well. This is not about getting a deep copy, but to merge custom properties and default values.

I use it to make the following writing more concise.

```ts
import { defaultSchema } from "rehype-sanitize"

const scheme = {
  ...defaultSchema,
  attributes: {
    ...defaultSchema.attributes,
    "*": [...(defaultSchema.attributes?.["*"] || []), "className", "style"],
    video: ["src", "controls", "loop", "muted", "autoPlay", "playsInline"],
  protocols: {
    ...defaultSchema.protocols,
    href: [...(defaultSchema.protocols?.href ?? []), ...["magnet", "ed2k"]],
  },
}

export default scheme
```

Comment (hyoban) [reply src/markdown/sanitize-schema.ts:1]: Or do you mistook `deepmerge` for `deepclone`?

Comment (DIYgod) [reply src/markdown/sanitize-schema.ts:1]: oh sorry, I got confused.
